apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: app1
spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            component: app1-executor
    strategy:
        rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                component: app1-executor
        spec:
            containers:
            -   image: app1
                name: app1


