apiVersion: apps/v1
kind: Deployment
metadata:
    name: app2
spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            component: app2-executor
    strategy:
        rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                component: app2-executor
        spec:
            containers:
            -   image: app2
                name: app2


